# Generated by Django 5.1.2 on 2024-10-31 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("question", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="QuestionModel",
        ),
    ]
