# Generated by Django 5.1.2 on 2024-10-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notice", "0003_rename_notices_noticemodel"),
    ]

    operations = [
        migrations.RenameField(
            model_name="noticemodel",
            old_name="view_count",
            new_name="hits",
        ),
        migrations.RenameField(
            model_name="noticemodel",
            old_name="is_lock",
            new_name="lockon",
        ),
    ]
